contact: # Optional, able to add e-mail/url
description:
dateformat:
defaultGoogleFonts:
googlefonts:
enableHighlight: true
amazonAssociateId: # Optional, Include amazon affiliate ID(eg. hikaeme-22)
since: # you can add the start period
defaultThumbnailUrl: # https://~ format is also supported
logoImageUrl: # https://~ format is also supported
copyright:
contactUrl: # Optional, if you want to add a contact form / sns accFount please write the URL here
enableAlgolia: true
logoFontFamily:
favicon:
  defaultUrl: # Required, add a url to the 32x32 size image. eg: "img/icon.webp"
  svgUrl: # Required, add a url to the svg image
  appleUrl: # Required, add the url to the 180x180 size image
twitterXId: # Optional, add the account id like => "@example-id"

author:
  thumbnailUrl:
  name:
  comment:
  sns:
    github:
      icon:
      url:
  # Optional, if you are using GitHub Sponsors, you can add the url
  githubSponsorUrl:
  githubSponsorButtonUrl:

algolia:
  vars:
    - "title"
    - "summary"
    - "content"
    - "date"
    - "publishdate"
    - "permalink"
    - "keywords"
  params:
    - "tags"
    - "categories"
  indexName:
  appId:
  searchOnlyApiKey: # https://www.algolia.com/doc/guides/security/api-keys/#search-only-api-key