plugins:
  - "prettier-plugin-go-template"
trailingComma: "es5"
singleQuote: false
goTemplateBracketSpacing: true

overrides:
  - files: "*.html"
    options:
      bracketSpacing: true
      parser: "go-template"

  - files:
    - "*.scss"
    - "*.css"
    options:
      parser: "scss"
