plugins:
  - "prettier-plugin-go-template"
trailingComma: "es5"
singleQuote: false
goTemplateBracketSpacing: true
tabWidth: 2

overrides:
  - files: "*.html"
    options:
      bracketSpacing: true
      parser: "go-template"

  - files:
      - "*.scss"
      - "*.css"
    options:
      parser: "scss"

  - files: "*.ts"
    options:
      parser: typescript
      singleQuote: false
      trailingComma: "es5"

  - files: "*.js"
    options:
      parser: babel
      singleQuote: false
      trailingComma: "all"
