plugins:
  - "prettier-plugin-go-template"
trailingComma: "es5"
goTemplateBracketSpacing: true
overrides:
  - files: "*.html"
    options:
      bracketSpacing: true
      parser: "go-template"
      singleQuote: false

  - files:
    - "*.scss"
    - "*.css"
    options:
      parser: "scss"
